/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package template;

import java.io.File;
import java.util.concurrent.Callable;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import picocli.CommandLine;

@CommandLine.Command(
    description = "TEMPLATE",
    name = "TEMPLATE", mixinStandardHelpOptions = true, version = "TEMPLATE 1.0")
public class App implements Callable<Integer> {
  private static final Logger logger = LoggerFactory.getLogger(App.class);

  @CommandLine.Option(names = {"-i", "--input"}, description = "Input directory", required = true)
  private File inputDir;

  @CommandLine.Option(names = {"-o", "--output"}, description = "Output directory", required = true)
  private File outputDir;

  public static void main(String[] args) {
    int exitCode = new CommandLine(new App()).execute(args);
    System.exit(exitCode);
  }

  @Override
  public Integer call() {
    try {
      logger.info("Hello, world!");
      logger.info("Input dir: {}, output dir: {}", inputDir, outputDir);
      return 0;
    } catch (RuntimeException e) {
      logger.error("Failed: {}", e.getMessage());
      return -1;
    }
  }
}
